// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd_Z14yqwKmGyyIlkzdcd55vznGOxIsGc',
    appId: '1:85961672220:web:79f7407ed35e3af07d41d9',
    messagingSenderId: '85961672220',
    projectId: 'shoesavvy-app',
    authDomain: 'shoesavvy-app.firebaseapp.com',
    storageBucket: 'shoesavvy-app.appspot.com',
    measurementId: 'G-QYDC8W2FVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXJkKVx_BpL95GZgxmQBD3hxraN7yr-HM',
    appId: '1:85961672220:android:4461cc64a6b4db127d41d9',
    messagingSenderId: '85961672220',
    projectId: 'shoesavvy-app',
    storageBucket: 'shoesavvy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCp7OG9jDmo4lwTQYVQDumniCYmSHHop2w',
    appId: '1:85961672220:ios:044a5e9d0275cb547d41d9',
    messagingSenderId: '85961672220',
    projectId: 'shoesavvy-app',
    storageBucket: 'shoesavvy-app.appspot.com',
    iosBundleId: 'com.example.shoesavvyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCp7OG9jDmo4lwTQYVQDumniCYmSHHop2w',
    appId: '1:85961672220:ios:96a29d837f64bc167d41d9',
    messagingSenderId: '85961672220',
    projectId: 'shoesavvy-app',
    storageBucket: 'shoesavvy-app.appspot.com',
    iosBundleId: 'com.example.shoesavvyApp.RunnerTests',
  );
}
